name: Deploy to Play Store

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java setup (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: gradlew permissions
        run: chmod +x gradlew

      - name: Inject API Keys into local.properties
        run: |
          echo "SHAKEKEY=\"${{ secrets.SHAKE_API_KEY }}\"" > local.properties
          echo "APIKEY=\"${{ secrets.YOUTUBE_API_KEY }}\"" >> local.properties

      - name: Build app bundle (.aab)
        run: ./gradlew bundleRelease

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload on Google Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_AUTH_JSON }}
          packageName: com.ctrlvnt.rytm
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: production
          status: completed